#!/bin/bash

# ClarusAI Azure Deployment Script
# This script helps deploy ClarusAI to Azure App Service

echo "🏥 ClarusAI Healthcare AI Platform - Azure Deployment"
echo "====================================================="

# Variables (you'll need to set these)
RESOURCE_GROUP="ClarusAI-RG"
APP_SERVICE_PLAN="ClarusAI-Plan"
WEB_APP_NAME="clarusai-webapp"
LOCATION="eastus"
SQL_SERVER_NAME="clarusai-sql-server"
DATABASE_NAME="ClarusAI"

echo "📋 Pre-deployment checklist:"
echo "  ✅ Application built successfully"
echo "  ✅ Security vulnerabilities fixed"
echo "  ✅ BCrypt password hashing implemented"
echo "  ✅ Environment variables configured"
echo ""

echo "🔧 Required Azure CLI commands to run manually:"
echo ""
echo "1. Login to Azure:"
echo "   az login"
echo ""
echo "2. Create Resource Group:"
echo "   az group create --name $RESOURCE_GROUP --location $LOCATION"
echo ""
echo "3. Create App Service Plan:"
echo "   az appservice plan create --name $APP_SERVICE_PLAN --resource-group $RESOURCE_GROUP --sku B1 --is-linux"
echo ""
echo "4. Create Web App:"
echo "   az webapp create --resource-group $RESOURCE_GROUP --plan $APP_SERVICE_PLAN --name $WEB_APP_NAME --runtime 'DOTNETCORE|8.0'"
echo ""
echo "5. Create SQL Server:"
echo "   az sql server create --name $SQL_SERVER_NAME --resource-group $RESOURCE_GROUP --location $LOCATION --admin-user clarusadmin --admin-password 'YourSecurePassword123!'"
echo ""
echo "6. Create SQL Database:"
echo "   az sql db create --resource-group $RESOURCE_GROUP --server $SQL_SERVER_NAME --name $DATABASE_NAME --service-objective Basic"
echo ""
echo "7. Configure firewall (allow Azure services):"
echo "   az sql server firewall-rule create --resource-group $RESOURCE_GROUP --server $SQL_SERVER_NAME --name AllowAzureServices --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0"
echo ""
echo "8. Set environment variables:"
echo "   az webapp config appsettings set --resource-group $RESOURCE_GROUP --name $WEB_APP_NAME --settings \\"
echo "     CLARUSAI_JWT_SECRET='$(openssl rand -base64 32)' \\"
echo "     CLARUSAI_CONNECTION_STRING='Server=tcp:$SQL_SERVER_NAME.database.windows.net,1433;Database=$DATABASE_NAME;User ID=clarusadmin;Password=YourSecurePassword123!;Encrypt=true;TrustServerCertificate=false;Connection Timeout=30;' \\"
echo "     ASPNETCORE_ENVIRONMENT='Production'"
echo ""
echo "9. Deploy application:"
echo "   az webapp deployment source config-zip --resource-group $RESOURCE_GROUP --name $WEB_APP_NAME --src ./publish.zip"
echo ""
echo "10. Configure custom domain (medcore.live):"
echo "    az webapp config hostname add --webapp-name $WEB_APP_NAME --resource-group $RESOURCE_GROUP --hostname medcore.live"
echo "    az webapp config ssl bind --certificate-thumbprint [CERT_THUMBPRINT] --ssl-type SNI --name $WEB_APP_NAME --resource-group $RESOURCE_GROUP"
echo ""

echo "🔐 Security Environment Variables to Set:"
echo "  CLARUSAI_JWT_SECRET: Strong random key (32+ characters)"
echo "  CLARUSAI_CONNECTION_STRING: SQL Database connection"
echo "  ASPNETCORE_ENVIRONMENT: Production"
echo ""

echo "📦 Application published to: ./publish/"
echo "💡 Create publish.zip: cd publish && zip -r ../publish.zip ."
echo ""
echo "🌐 After deployment, your app will be available at:"
echo "  https://$WEB_APP_NAME.azurewebsites.net"
echo "  https://medcore.live (after custom domain setup)"
echo ""

echo "✅ Deployment preparation complete!"
echo "   Run the Azure CLI commands above to deploy to Azure."